# Generated by Django 3.2.6 on 2021-08-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresumeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
